AVM-Review-PR
Azure/terraform-azurerm-avm-ptn-function-app-storage-private-endpoints pull request #14
Opened 2024-09-12 15:53 UTC by donovm4

2024-11-01 09:19 UTC, jaredfholgate commented
@donovm4 Is this PR ready for review?

2024-11-20 14:02 UTC, donovm4 commented
@jaredfholgate : this module is now ready for a review 👍

2025-02-14 00:00 UTC, MikeDembek commented
Any progress on this?

2025-02-18 18:47 UTC, donovm4 commented
@MikeDembek : there are some additional spec items that I need to account for, but will be looking to get the final updated review and publishing done soon.

2025-04-07 19:57 UTC, jchancellor-ms commented on examples/default/terraform.tf
> +  subscription_id = "<subcription_id>"
You should comment the subscription_ID to avoid issues with it trying to inject the dummy value.

2025-04-07 20:12 UTC, jchancellor-ms requested changes
Please do a quick review on the contents. Also, just for awareness, we are in the process of releasing new OPA tests for App service plans.  So any ASP that gets installed will need to have zone_balancing_enabled == true, and use either a premium or standard sku.  So you may want to validate your examples/module use these defaults.

2025-04-07 20:12 UTC, jchancellor-ms commented on variables.function_app.tf
> +# variable "new_service_plan" {
What happened to this input's capabilities?  If it is deprecated, then we should handle deprecation.

2025-04-08 14:16 UTC, donovm4 commented on variables.function_app.tf
> +# variable "new_service_plan" {
Do I need to document this variable as deprecated since this is pre `0.1.0`?

I think I "deprecated" _very_ early on into the development - would it be okay to just remove it from the code?

Users will use `create_service_plan` and `service_plan` to specify the new ASP to be created.

2025-04-10 17:44 UTC, jchancellor-ms approved these changes
Approved

2025-04-10 17:49 UTC, merged